
type event_type =
   NO_EVENT| PUSH| RELEASE| ENTER| LEAVE| DRAG| FOCUS| UNFOCUS| 
   KEY| KEYUP| FOCUS_CHANGE| MOVE| SHORTCUT| DEACTIVATE| ACTIVATE| HIDE| 
   SHOW| PASTE| TIMEOUT| MOUSEWHEEL| DND_ENTER| DND_DRAG| DND_LEAVE| DND_RELEASE| 
   TOOLTIP
;;

external event_dy: unit -> int = "event_dy";;
